[package]
name = "picourl"
version = "0.1.0"
authors = ["juancho.villa@icloud.com <juancho.villa@icloud.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
